{
 "title": "Bucket Notifications",
 "tags": [
  "backbeat",
  "notification"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "notification_processor",
    "label": "Notification processor",
    "query": "label_values(s3_notification_queue_processor_events_total{namespace=\"${namespace}\", job=~\"${job_notification_processors}.*\", target=~\"${target}\"}, job)"
   },
   {
    "name": "target",
    "label": "Notification target",
    "query": "label_values(s3_notification_queue_processor_events_total{namespace=\"${namespace}\", job=~\"${job_notification_processors}.*\", target=~\".*\"}, target)"
   }
  ]
 },
 "panels": [
  { "title": "Service Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zookeeper Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(\nquorum_size{\n  namespace=\"${namespace}\",\n  job=\"${job_zookeeper}\"\n})"
    }
   ]
  },
  {
   "title": "Kafka Brokers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\nkafka_server_replicamanager_leadercount{\n namespace=\"${namespace}\",\n job=\"${job_kafka}\"\n})"
    }
   ]
  },
  {
   "title": "Notification producer",
   "type": "stat",
   "description": "Number of active notification producer instances",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{\n    namespace=\"${namespace}\",\n    job=\"${job_notification_producer}\"\n})"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_notification_queue_processor_delivery_delay_seconds_count{namespace=\"${namespace}\", job=~\"${notification_processor}\", target=~\"${target}\", status=\"success\"}[$__rate_interval]))\n/\nsum(rate(s3_notification_queue_processor_delivery_delay_seconds_count{namespace=\"${namespace}\", job=~\"${notification_processor}\", target=~\"${target}\", status=~\".*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Notification Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_notification_queue_processor_delivery_delay_seconds_count{namespace=\"${namespace}\", job=~\"${notification_processor}\", target=~\"${target}\", status=\"success\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Bandwidth Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(s3_notification_queue_processor_notification_size_total{namespace=\"${namespace}\", job=~\"${notification_processor}\", target=~\"${target}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Notification Processors",
   "type": "state-timeline",
   "description": "Active notification processor instances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "label_replace(\nsum by(job) (up{\n    namespace=\"${namespace}\",\n    job=~\"${notification_processor}\"\n}), \"job\", \"$1\", \"job\", \".*-(.*)-headless\")",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Notification Topics Lag",
   "type": "timeseries",
   "description": "Consumer lag of each of the notification topics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nmax by(topic) (\n    kafka_consumergroup_group_lag_seconds{       topic=~\"${notification_topics}\"\n}), \"topic\", \"$1\", \"topic\", \".*backbeat-notification-(.*).*\")",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Notification Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Notification Delivery Rate",
   "type": "timeseries",
   "description": "Number of delivered notifications in a given time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(target) (rate(s3_notification_queue_processor_delivery_delay_seconds_count{namespace=\"${namespace}\", job=~\"${notification_processor}\", target=~\"${target}\", status=\"success\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Failed Notifications Per Target In Time",
   "type": "timeseries",
   "description": "Number of failed notifications in a given time",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(target) (rate(s3_notification_queue_processor_delivery_delay_seconds_count{namespace=\"${namespace}\", job=~\"${notification_processor}\", target=~\"${target}\", status=\"failure\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Event Types Processed",
   "type": "timeseries",
   "description": "Number of notification events of a given type that where processed",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(eventType) (rate(s3_notification_queue_processor_events_total{namespace=\"${namespace}\", job=~\"${notification_processor}\", target=~\"${target}\"}[$__rate_interval]))",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  {
   "title": "Total Processed Oplog Events",
   "type": "timeseries",
   "description": "Number of processed oplog events by the notification producer",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(s3_notification_queue_populator_events_total{job=\"${job_notification_producer}\", namespace=\"${namespace}\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "description": "Bandwidth used to send notifications to targets in a given time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(target) (rate(s3_notification_queue_processor_notification_size_total{namespace=\"${namespace}\", job=~\"${notification_processor}\", target=~\"${target}\"}[$__rate_interval]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Delivery Delay",
   "type": "heatmap",
   "description": "Delay between when a notification is sent and when it is received",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(s3_notification_queue_processor_delivery_delay_seconds_sum{namespace=\"${namespace}\", job=~\"${notification_processor}\", target=~\"${target}\", status=\"success\"}[$__rate_interval])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Cache Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Cache Get Lag",
   "type": "timeseries",
   "description": "Time it takes to get a bucket notification config from MongoDB",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\nsum by(job) (rate(s3_notification_config_manager_config_get_seconds_sum{namespace=\"${namespace}\", job=~\"${notification_processor}|${job_notification_producer}\", cache_hit=\"true\"}[$__rate_interval]))\n, \"job\", \"$1\", \"job\", \".*-(.*)-headless\")",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Cache Updates",
   "type": "timeseries",
   "description": "Rate of cache updates",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(\nsum by (job) (rate (s3_notification_config_manager_cache_updates_total{namespace=\"${namespace}\", job=~\"${notification_processor}|${job_notification_producer}\"}[$__rate_interval]))\n, \"job\", \"$1\", \"job\", \".*-(.*)-headless\")",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cached Notification Configurations",
   "type": "timeseries",
   "description": "Total number of notification configurations cached",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "label_replace(\nsum(s3_notification_config_manager_cached_buckets_count{namespace=\"${namespace}\", job=~\"${notification_processor}|${job_notification_producer}\"}) by (job)\n, \"job\", \"$1\", \"job\", \".*-(.*)-headless\")",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss Ratio",
   "type": "gauge",
   "description": "Cache Hit/Miss Ratio",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(\nsum by (job) (rate (s3_notification_config_manager_config_get_seconds_count{namespace=\"${namespace}\", job=~\"${notification_processor}|${job_notification_producer}\", cache_hit=\"true\"}[$__rate_interval]))\n/\nsum by (job) (rate (s3_notification_config_manager_config_get_seconds_count{namespace=\"${namespace}\", job=~\"${notification_processor}|${job_notification_producer}\"}[$__rate_interval]))\n, \"job\", \"$1\", \"job\", \".*-(.*)-headless\")",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}